import { Quiz, Question } from '@/types';
import { v4 as uuidv4 } from 'uuid';

export const pflegeversicherungQuestions: Question[] = [
  // Question 1 - Easy warm-up
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Seit wann gibt es die Pflegeversicherung in Deutschland?',
    image: '📅',
    category: 'Geschichte',
    difficulty: 'easy',
    answers: [
      { id: uuidv4(), text: '1990', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '1995', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: '2000', isCorrect: false, color: 'yellow' },
      { id: uuidv4(), text: '2005', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1000,
    explanation: 'Die Pflegeversicherung wurde am 1. Januar 1995 als fünfte Säule der Sozialversicherung eingeführt.',
    funFact: 'Deutschland war eines der ersten Länder weltweit mit einer umfassenden Pflegeversicherung!',
    chartData: [
      { label: '1995', value: 1, color: '#00B4A6' },
      { label: 'Heute', value: 30, color: '#FFD166' },
    ],
    order: 1,
  },
  // Question 2 - Visual question about Pflegegrade
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wie viele Pflegegrade gibt es in Deutschland?',
    image: '📊',
    category: 'Grundlagen',
    difficulty: 'easy',
    answers: [
      { id: uuidv4(), text: '3 Pflegegrade', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '4 Pflegegrade', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: '5 Pflegegrade', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: '6 Pflegegrade', isCorrect: false, color: 'green' },
    ],
    timeLimit: 15,
    points: 1000,
    explanation: 'Es gibt 5 Pflegegrade (1-5), die den Grad der Pflegebedürftigkeit beschreiben.',
    funFact: 'Vor 2017 gab es noch das alte System mit 3 Pflegestufen!',
    chartData: [
      { label: 'PG 1', value: 12.5, color: '#4ECDC4' },
      { label: 'PG 2', value: 27, color: '#45B7D1' },
      { label: 'PG 3', value: 33, color: '#96CEB4' },
      { label: 'PG 4', value: 15.5, color: '#FFEAA7' },
      { label: 'PG 5', value: 12, color: '#DDA0DD' },
    ],
    order: 2,
  },
  // Question 3 - True/False
  {
    id: uuidv4(),
    type: 'true_false',
    text: 'Die Pflegeversicherung deckt ALLE Pflegekosten vollständig ab.',
    image: '💰',
    category: 'Finanzierung',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: 'Wahr', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: 'Falsch', isCorrect: true, color: 'red' },
    ],
    timeLimit: 15,
    points: 1000,
    explanation: 'FALSCH! Die Pflegeversicherung ist eine "Teilkasko" - sie deckt nur einen Teil der Kosten. Der Rest muss selbst gezahlt werden.',
    funFact: 'Im Durchschnitt müssen Pflegebedürftige ca. 2.400€ pro Monat selbst zahlen!',
    chartData: [
      { label: 'Kasse zahlt', value: 45, color: '#00B4A6' },
      { label: 'Eigenanteil', value: 55, color: '#FF6B6B' },
    ],
    order: 3,
  },
  // Question 4 - Estimate/Slider
  {
    id: uuidv4(),
    type: 'estimate',
    text: 'Wie viele Menschen in Deutschland sind pflegebedürftig?',
    image: '👥',
    category: 'Statistik',
    difficulty: 'hard',
    answers: [
      { id: uuidv4(), text: 'Ca. 2 Millionen', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: 'Ca. 3,5 Millionen', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: 'Ca. 5 Millionen', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: 'Ca. 7 Millionen', isCorrect: false, color: 'green' },
    ],
    correctValue: 5000000,
    unit: 'Menschen',
    minValue: 1000000,
    maxValue: 10000000,
    timeLimit: 20,
    points: 1500,
    explanation: 'Stand 2023 sind etwa 5 Millionen Menschen in Deutschland pflegebedürftig - Tendenz steigend!',
    funFact: 'Bis 2050 werden voraussichtlich über 6 Millionen Menschen pflegebedürftig sein.',
    chartData: [
      { label: '2000', value: 2, color: '#96CEB4' },
      { label: '2010', value: 2.4, color: '#45B7D1' },
      { label: '2020', value: 4.1, color: '#FFEAA7' },
      { label: '2023', value: 5, color: '#FF6B6B' },
    ],
    order: 4,
  },
  // Question 5 - Beitragssatz
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wie hoch ist der aktuelle Beitragssatz zur Pflegeversicherung (2024, mit Kind)?',
    image: '💸',
    category: 'Beiträge',
    difficulty: 'hard',
    answers: [
      { id: uuidv4(), text: '2,3%', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '3,05%', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: '3,4%', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: '4,0%', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1500,
    explanation: 'Der Beitragssatz beträgt 3,4% des Bruttoeinkommens für Personen mit Kindern.',
    funFact: 'Kinderlose zahlen einen Zuschlag von 0,6% - also insgesamt 4,0%!',
    chartData: [
      { label: '1995', value: 1, color: '#96CEB4' },
      { label: '2005', value: 1.7, color: '#45B7D1' },
      { label: '2015', value: 2.35, color: '#FFEAA7' },
      { label: '2024', value: 3.4, color: '#FF6B6B' },
    ],
    order: 5,
  },
  // Question 6 - Pflegegeld
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Ab welchem Pflegegrad bekommt man Pflegegeld?',
    image: '🏦',
    category: 'Leistungen',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: 'Ab Pflegegrad 1', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: 'Ab Pflegegrad 2', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: 'Ab Pflegegrad 3', isCorrect: false, color: 'yellow' },
      { id: uuidv4(), text: 'Ab Pflegegrad 4', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1000,
    explanation: 'Pflegegeld gibt es erst ab Pflegegrad 2. Bei Pflegegrad 1 erhält man nur den Entlastungsbetrag von 125€.',
    funFact: 'Das Pflegegeld kann frei verwendet werden - für Angehörige oder was auch immer hilft!',
    chartData: [
      { label: 'PG 1', value: 0, color: '#ccc' },
      { label: 'PG 2', value: 332, color: '#45B7D1' },
      { label: 'PG 3', value: 573, color: '#96CEB4' },
      { label: 'PG 4', value: 765, color: '#FFEAA7' },
      { label: 'PG 5', value: 947, color: '#FF6B6B' },
    ],
    order: 6,
  },
  // Question 7 - True/False Pflichtversicherung
  {
    id: uuidv4(),
    type: 'true_false',
    text: 'Jeder in Deutschland MUSS pflegeversichert sein.',
    image: '⚖️',
    category: 'Recht',
    difficulty: 'easy',
    answers: [
      { id: uuidv4(), text: 'Wahr', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: 'Falsch', isCorrect: false, color: 'red' },
    ],
    timeLimit: 15,
    points: 1000,
    explanation: 'RICHTIG! Die Pflegeversicherung ist eine Pflichtversicherung - wer krankenversichert ist, ist automatisch auch pflegeversichert.',
    funFact: 'Die Pflegeversicherung ist die jüngste der 5 Säulen der Sozialversicherung!',
    order: 7,
  },
  // Question 8 - Wer begutachtet?
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wer stellt den Pflegegrad fest?',
    image: '🩺',
    category: 'Verfahren',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: 'Der Hausarzt', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: 'Der Medizinische Dienst (MD)', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: 'Das Sozialamt', isCorrect: false, color: 'yellow' },
      { id: uuidv4(), text: 'Die Krankenkasse selbst', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1000,
    explanation: 'Der Medizinische Dienst (MD) führt die Begutachtung durch. Bei Privatversicherten macht das MEDICPROOF.',
    funFact: 'Eine Begutachtung dauert meist 45-90 Minuten und findet zu Hause statt!',
    order: 8,
  },
  // Question 9 - Kombinationsleistung
  {
    id: uuidv4(),
    type: 'true_false',
    text: 'Man kann Pflegegeld und Pflegesachleistungen kombinieren.',
    image: '🔄',
    category: 'Leistungen',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: 'Wahr', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: 'Falsch', isCorrect: false, color: 'red' },
    ],
    timeLimit: 15,
    points: 1000,
    explanation: 'RICHTIG! Das nennt sich "Kombinationsleistung" - man kann beide Leistungsarten anteilig nutzen.',
    funFact: 'Die meisten Pflegebedürftigen nutzen tatsächlich eine Kombination aus beiden!',
    chartData: [
      { label: 'Nur Geld', value: 52, color: '#00B4A6' },
      { label: 'Kombi', value: 30, color: '#FFD166' },
      { label: 'Nur Sach', value: 18, color: '#FF6B6B' },
    ],
    order: 9,
  },
  // Question 10 - Pflegegeld Höhe PG5
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wie hoch ist das monatliche Pflegegeld bei Pflegegrad 5 (2024)?',
    image: '💵',
    category: 'Leistungen',
    difficulty: 'hard',
    answers: [
      { id: uuidv4(), text: '765 Euro', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '901 Euro', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: '947 Euro', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: '1.100 Euro', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1500,
    explanation: 'Das Pflegegeld bei Pflegegrad 5 beträgt 947 Euro monatlich (Stand 2024 nach Erhöhung).',
    funFact: 'Das Pflegegeld wurde 2024 um 5% erhöht!',
    chartData: [
      { label: 'PG 2', value: 332, color: '#96CEB4' },
      { label: 'PG 3', value: 573, color: '#45B7D1' },
      { label: 'PG 4', value: 765, color: '#FFEAA7' },
      { label: 'PG 5', value: 947, color: '#FF6B6B' },
    ],
    order: 10,
  },
  // Question 11 - Vorversicherungszeit
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wie lange muss man versichert sein, bevor man Leistungen erhält?',
    image: '⏰',
    category: 'Voraussetzungen',
    difficulty: 'hard',
    answers: [
      { id: uuidv4(), text: '6 Monate', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '12 Monate', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: '2 Jahre in den letzten 10 Jahren', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: '5 Jahre', isCorrect: false, color: 'green' },
    ],
    timeLimit: 25,
    points: 1500,
    explanation: 'Die Vorversicherungszeit beträgt 2 Jahre innerhalb der letzten 10 Jahre vor Antragstellung.',
    funFact: 'Für Kinder gilt diese Frist übrigens nicht - sie sind über ihre Eltern mitversichert!',
    order: 11,
  },
  // Question 12 - Was bedeutet Pflegesachleistung?
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Was sind "Pflegesachleistungen"?',
    image: '🏠',
    category: 'Leistungen',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: 'Geld für pflegende Angehörige', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: 'Pflege durch professionelle Pflegedienste', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: 'Hilfsmittel wie Rollstühle', isCorrect: false, color: 'yellow' },
      { id: uuidv4(), text: 'Umbaumaßnahmen in der Wohnung', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1000,
    explanation: 'Pflegesachleistungen = Professionelle Pflege durch ambulante Pflegedienste zu Hause.',
    funFact: 'Die Sachleistungsbeträge sind deutlich höher als das Pflegegeld!',
    chartData: [
      { label: 'PG 2 Geld', value: 332, color: '#96CEB4' },
      { label: 'PG 2 Sach', value: 761, color: '#FF6B6B' },
    ],
    order: 12,
  },
  // Question 13 - Wo leben die meisten Pflegebedürftigen?
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wo werden die meisten Pflegebedürftigen versorgt?',
    image: '🏡',
    category: 'Statistik',
    difficulty: 'easy',
    answers: [
      { id: uuidv4(), text: 'Im Pflegeheim', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: 'Im Krankenhaus', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: 'Zu Hause', isCorrect: true, color: 'yellow' },
      { id: uuidv4(), text: 'In Tagespflegeeinrichtungen', isCorrect: false, color: 'green' },
    ],
    timeLimit: 15,
    points: 1000,
    explanation: 'Über 80% aller Pflegebedürftigen werden zu Hause versorgt - meist von Angehörigen!',
    funFact: 'Etwa 4 Millionen Menschen pflegen Angehörige - oft unbezahlt neben ihrem Job.',
    chartData: [
      { label: 'Zu Hause', value: 84, color: '#00B4A6' },
      { label: 'Pflegeheim', value: 16, color: '#FF6B6B' },
    ],
    order: 13,
  },
  // Question 14 - Entlastungsbetrag
  {
    id: uuidv4(),
    type: 'multiple_choice',
    text: 'Wie hoch ist der monatliche Entlastungsbetrag?',
    image: '🎁',
    category: 'Leistungen',
    difficulty: 'medium',
    answers: [
      { id: uuidv4(), text: '75 Euro', isCorrect: false, color: 'red' },
      { id: uuidv4(), text: '125 Euro', isCorrect: true, color: 'blue' },
      { id: uuidv4(), text: '200 Euro', isCorrect: false, color: 'yellow' },
      { id: uuidv4(), text: '250 Euro', isCorrect: false, color: 'green' },
    ],
    timeLimit: 20,
    points: 1000,
    explanation: 'Der Entlastungsbetrag beträgt 125€ pro Monat für alle Pflegegrade - auch für Pflegegrad 1!',
    funFact: 'Der Betrag kann für Haushaltshilfen, Betreuung oder Tagespflege genutzt werden.',
    order: 14,
  },
  // Question 15 - Final Boss Question
  {
    id: uuidv4(),
    type: 'true_false',
    text: 'Arbeitgeber und Arbeitnehmer teilen sich den Pflegeversicherungsbeitrag genau hälftig.',
    image: '🤝',
    category: 'Beiträge',
    difficulty: 'hard',
    answers: [
      { id: uuidv4(), text: 'Wahr', isCorrect: false, color: 'blue' },
      { id: uuidv4(), text: 'Falsch', isCorrect: true, color: 'red' },
    ],
    timeLimit: 20,
    points: 2000,
    explanation: 'FALSCH! In Sachsen zahlt der Arbeitnehmer mehr. Außerdem zahlen Kinderlose den Zuschlag allein!',
    funFact: 'In Sachsen wurde dafür der Buß- und Bettag als Feiertag gestrichen.',
    chartData: [
      { label: 'AN normal', value: 1.7, color: '#45B7D1' },
      { label: 'AG normal', value: 1.7, color: '#96CEB4' },
      { label: 'AN Sachsen', value: 2.2, color: '#FF6B6B' },
      { label: 'AG Sachsen', value: 1.2, color: '#FFEAA7' },
    ],
    order: 15,
  },
];

export const defaultQuiz: Quiz = {
  id: 'default-pflegeversicherung',
  title: 'Pflegeversicherung',
  description: 'Teste dein Wissen über die deutsche Pflegeversicherung!',
  questions: pflegeversicherungQuestions,
  createdAt: new Date(),
};

export function generateGameCode(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}
